version: '3.7'

services:
  proxy:
    image: localhost:5000/nitrox-proxy
    environment:
      NITROX_DISCOVERY: discovery:3000
      NITROX_SERVICE: nitrox/proxy
      NITROX_ENVIRONMENT: production
      NITROX_HOST: 172.17.0.1
      NITROX_PORT: 3500
    volumes:
      - ./data/proxy:/nitrox/app/service/nitrox-proxy/data
    depends_on:
      - discovery
    ports:
      - 3500:3500

  connector:
    image: localhost:5000/nitrox-connector
    environment:
      NITROX_DISCOVERY: discovery:3000
      NITROX_SERVICE: nitrox/connector
      NITROX_ENVIRONMENT: production
      NITROX_HOST: connector
      NITROX_PORT: 3000
    volumes:
      - ./data/connector:/nitrox/app/service/nitrox-connector/data
    depends_on:
      - discovery

  discovery:
    image: localhost:5000/nitrox-discovery
    environment:
      NITROX_SERVICE: nitrox/discovery
      NITROX_ENVIRONMENT: production
      NITROX_HOST: discovery
      NITROX_PORT: 3000
      NITROX_MEMCACHED: 172.17.0.1:11211
      NITROX_REDPANDA: 172.17.0.1:9092
      NITROX_REDPANDA_CONSOLE: 172.17.0.1:8089
      NITROX_BADGER_DB: 172.17.0.1:9701
    volumes:
      - ./data/discovery:/nitrox/app/service/nitrox-discovery/data
    depends_on:
      - redpanda
      - memcached
      - badger-db

  badger-db:
    image: icebaker/badger-db:0.0.1
    environment:
      BADGER_DB_DATA_PATH: /badger-db/data
      BADGER_DB_CONTEXT: nitrox
      BADGER_DB_HOST: 0.0.0.0
      BADGER_DB_PORT: 9701
    volumes:
      - ./data/badger-db:/badger-db/data
    ports:
      - 9701:9701

  memcached:
    image: memcached:1.6.18-bullseye
    command: ['-m', '64m']
    ports:
      - 11211:11211

  redpanda:
    image: redpandadata/redpanda:v23.1.3
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --memory 128M
      - --reserve-memory 0M
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 9092:9092

  redpanda-console:
    image: redpandadata/console:v2.2.3
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8089:8080
    depends_on:
      - redpanda
