# frozen_string_literal: true

ruby '3.2.1'

source 'https://rubygems.org'

gem 'nitrox-core', path: '../../nitrox-core'

gem 'dotenv', '~> 2.8', '>= 2.8.1'

gem 'rack', '~> 3.0', '>= 3.0.7'
gem 'rack-cors', '~> 2.0', '>= 2.0.1'
gem 'rackup', '~> 2.1'

gem 'puma', '~> 6.1', '>= 6.1.1'
gem 'roda', '~> 3.66'

gem 'faraday', '~> 2.7', '>= 2.7.4'

group :test, :development do
  gem 'pry-byebug', '~> 3.10', '>= 3.10.1'
  gem 'rerun', '~> 0.14.0'
  gem 'rubocop', '~> 1.48', '>= 1.48.1'
end
